language: cn           # en, cn
theme: dark           # white, dark
initial_cash: 5000.0
#------------------------begin accouts-------------------------#

 #--------------------------end of accounts---------------------



#-------------- active strategies -------------#
strategy:
  MovingAverageCrossStrategy:
    short_window: 2
    long_window: 8
    symbols:
      -  ZCE F CF 809
#  TestStrategy:
#    symbols:
#      - SHFE F NI 1811
#----------------end of strategies-----------------