strategy: TestStrategy
cash: 500000.00
tickers:
  #- AMZN
  #- AAPL
  #- 600000
  #- AL01
  #- SRX05
  - RU01
  #- TAMI
  #- MA05
  #- MAMI
benchmark:            # or leave it empty
start_date: 2018-04-10 09:00:00
end_date: 2018-04-27 15:00:00
datasource: local   # local, quandl, tushare
hist_dir: /home/wubin/EliteQuant_Python/hist
output_dir: /home/wubin/EliteQuant_Python/out
