strategy: BreakThroughStrategy
cash: 500000.00
tickers:
  #- AMZN
  #- AAPL
  #- 600000
  #- AL01
  #- SRX05
  - RB10
  #- TAMI
  #- MA05
  #- MAMI
benchmark:            # or leave it empty
start_date: 2018-04-02 09:00:00
end_date: 2018-04-20 15:00:00
datasource: local   # localcsv, localmongodb,quandl, tushare
hist_dir: ./data
output_dir: ./result
