#------------------ System Setting --------------#
mode: trade      #trade, replay,
filetoreplay: test.txt
tickinterval: 1000
brokerdelay: 100
msgq: nanomsg           # nanomsg kafka, zmq
log_dir: ./log
data_dir: ./data
dbaddr: mongodb://localhost:27017
dbname: ftick
apis:
  - CTP
 # - TAP
serverpub_url: ipc://pub
serversub_url: ipc://sub
serverpull_url: ipc://pull
#------------------ End of System ---------------#
accounts:

#--------------------api setting---------------------#

CTP: # SimNow仿真
  api: CTP
  intid: 1
  brokerid: 9999
  userid: 
  password: 
  auth_code: NA             # NA or actual auth code
  user_prod_info: NA        # NA or actual user info
  md_ip: tcp://180.168.146.187 #10010/11/13/56 218.202.237.33:10012
  md_port: 10010
  td_ip: tcp://180.168.146.187 #10000/1/3/50   218.202.237.33:10002
  td_port: 10001
CTP1:    # 招商期货仿真
  api: CTP
  intid: 1
  brokerid: 8060
  userid: 
  password: 
  auth_code: CMFTESTPUBCODE01             #
  user_prod_info: CMFTEST        # 直连模式，中继模式RELAYCMFTEST
  md_ip: tcp://140.206.80.234 # 联通，电信：180.166.65.114
  md_port: 31213
  td_ip: tcp://140.206.80.234 
  td_port: 31205
  
TAP: #易盛
  api: TAP
  intid: 2
  brokerid: 9999
  userid: 
  password: 
  auth_code: 67EA896065459BECDFDB924B29CB7DF1946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC5211AF9FEE541DDE41BCBAB68D525B0D111A0884D847D57163FF7F329FA574E7946CED32E26C1EAC946CED32E26C1EAC733827B0CE853869ABD9B8F170E14F8847D3EA0BF4E191F5D97B3DFE4CCB1F01842DD2B3EA2F4B20CAD19B8347719B7E20EA1FA7A3D1BFEFF22290F4B5C43E6C520ED5A40EC1D50ACDF342F46A92CCF87AEE6D73542C42EC17818349C7DEDAB0E4DB16977714F873D505029E27B3D57EB92D5BEDA0A710197EB67F94BB1892B30F58A3F211D9C3B3839BE2D73FD08DD776B9188654853DDA57675EBB7D6FBBFC
  user_prod_info: NA        # NA or actual user info
  md_ip: 123.161.206.213
  md_port: 6161
  td_ip: 61.163.243.173
  td_port: 6160

#--------------------End of api setting---------------------#

tickers:
  - SHFE F RB 1906

